import { MetadataRoute } from "next";

const BASE = "https://www.mktweb360.com";

export default function sitemap(): MetadataRoute.Sitemap {
  const pages = [
    { url: "/", priority: 1.0, changeFrequency: "weekly" as const },
    { url: "/seo-posicionamiento-web-organico/", priority: 0.9, changeFrequency: "monthly" as const },
    { url: "/seo-local/", priority: 0.9, changeFrequency: "monthly" as const },
    { url: "/marketing-shopware/", priority: 0.9, changeFrequency: "monthly" as const },
    { url: "/geo-posicionamiento-ia-chatgpt-empresas-espana/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/cuanto-cuesta-agencia-marketing-digital-espana-2026/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/seo-para-clinicas-centros-salud-captar-pacientes-google/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/woocommerce-vs-shopify-cual-elegir-tienda-online/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/seo-shopware-posicionar-tienda-google/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/google-ads-shopware-campanas-que-venden/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/migrar-shopware-prestashop-woocommerce-seo/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/geo-shopware-agentic-commerce-chatgpt/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/cro-shopware-optimizar-conversion-tienda/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/sem-publicidad-ppc/", priority: 0.9, changeFrequency: "monthly" as const },
    { url: "/smm-social-media-marketing/", priority: 0.9, changeFrequency: "monthly" as const },
    { url: "/diseno-de-paginas-web/", priority: 0.9, changeFrequency: "monthly" as const },
    { url: "/diseno-de-paginas-web/paginas-corporativas/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/diseno-de-paginas-web/diseno-tiendas-online/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/diseno-de-paginas-web/diseno-paginas-web-empresa/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/marketing-de-contenidos/", priority: 0.9, changeFrequency: "monthly" as const },
    { url: "/cuanto-cuesta-pagina-web-profesional/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/seo-o-google-ads-que-conviene-mas/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/seo-local-empresas-servicios/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/que-revisar-antes-de-invertir-mas-en-marketing-digital/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/senales-web-necesita-rediseno/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/como-generar-leads-calidad-pyme/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/seo-para-ecommerce-errores-que-frenan-ventas/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/que-puede-automatizar-una-pyme-en-marketing-y-ventas/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/ia-aplicada-a-marketing-valor-real-o-humo/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/como-puede-un-autonomo-conseguir-clientes-por-internet/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/nosotros/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/auditoria-digital/", priority: 0.9, changeFrequency: "monthly" as const },
    { url: "/comunicacion-audiovisual/", priority: 0.9, changeFrequency: "monthly" as const },
    { url: "/casos/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/blog/", priority: 0.8, changeFrequency: "weekly" as const },
    { url: "/oferta-web-seo/", priority: 0.9, changeFrequency: "monthly" as const },
    { url: "/oferta-seo/", priority: 0.9, changeFrequency: "weekly" as const },
    { url: "/oferta-seo-geo-gbp/", priority: 0.9, changeFrequency: "weekly" as const },
    { url: "/contacto/", priority: 0.7, changeFrequency: "yearly" as const },
    { url: "/aviso-legal/", priority: 0.3, changeFrequency: "yearly" as const },
    { url: "/politica-de-privacidad/", priority: 0.3, changeFrequency: "yearly" as const },
    { url: "/politica-de-cookies/", priority: 0.3, changeFrequency: "yearly" as const },
    { url: "/seo-para-servicios-urgentes-24h/", priority: 0.6, changeFrequency: "yearly" as const },
    { url: "/como-crear-una-pagina-web-para-pintores-y-conseguir-clientes-en-google/", priority: 0.6, changeFrequency: "yearly" as const },
    { url: "/todo-lo-que-necesitas-saber-sobre-el-analisis-dafo-en-tu-estrategia-de-marketing/", priority: 0.6, changeFrequency: "yearly" as const },
    { url: "/descubre-el-poder-del-canvas-para-la-gestion-de-tus-redes-sociales/", priority: 0.6, changeFrequency: "yearly" as const },
    { url: "/descubre-el-analisis-pestel-en-el-marketing-digital/", priority: 0.6, changeFrequency: "yearly" as const },
    { url: "/como-elegir-el-mejor-hosting-para-tu-web/", priority: 0.6, changeFrequency: "yearly" as const },
    { url: "/ha-muerto-el-seo-con-la-ia/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/como-darse-de-alta-autonomo/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/factura-electronica-obligatoria-autonomos-pymes/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/como-digitalizar-tu-negocio/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/google-my-business-empresas-guia/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/como-crear-propuesta-de-valor/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/errores-digitales-negocio-nuevo/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/como-gestionar-reputacion-online-empresa/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/google-merchant-center-ecommerce-guia/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/google-business-profile/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/creacion-de-blog/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/whatsapp-marketing/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/tienda-online/", priority: 0.9, changeFrequency: "monthly" as const },
    { url: "/ia-aplicada-al-marketing/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/geo-posicionamiento-ia/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/marketing-digital-toledo/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/seo-toledo/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/digitalizacion-empresas-castilla-la-mancha/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/agencias-marketing-digital-toledo/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/tiendas-online-toledo/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/google-business-profile-toledo/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/que-es-geo-generative-engine-optimization/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/como-crear-landing-page-que-convierte/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/whatsapp-business-para-empresas/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/email-marketing-pymes/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/como-medir-roi-marketing-digital/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/gestion-resenas-negativas-google/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/diseno-web-pymes/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/importar-productos-woocommerce/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/conectar-tpv-tienda-online/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/migrar-tienda-online-sin-perder-datos/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/seo-madrid/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/migrar-shopify-woocommerce/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/marketing-digital-barcelona/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/metodos-pago-tienda-online-espana/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/seo-valencia/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/auditoria-seo-basica/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/chatgpt-para-marketing-digital/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/marketing-digital-sevilla/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/google-shopping-tiendas-online/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/seo-bilbao/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/link-building-pymes/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/agencias-marketing-digital-madrid/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/configurar-envios-woocommerce/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/diseno-web-barcelona/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/geo-vs-seo-diferencias/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/seo-zaragoza/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/cuando-elegir-seo-vs-google-ads/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog-monetizacion/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/ecommerce-participacion-resultados/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/analitica-web/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/email-marketing/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/reputacion-online/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/diseno-web-para-clinicas/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/diseno-web-para-coaches/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/diseno-web-para-dentistas/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/diseno-web-tienda-online/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/como-usar-planificador-de-palabras-clave-google-ads/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/ejemplos-y-diferencias-entre-buscadores-y-navegadores/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/instagram-para-empresas-que-poner-en-la-biografia-de-instagram/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/por-que-aparecer-en-chatgpt-perplexity-gemini-importa-mas-que-el-seo-en-2026/", priority: 0.7, changeFrequency: "weekly" as const },
    { url: "/como-optimizar-tu-contenido-para-que-la-ia-te-cite-guia-geo-2026/", priority: 0.7, changeFrequency: "weekly" as const },
    { url: "/geo-para-pymes-como-aparecer-en-respuestas-ia-sin-ser-una-gran-marca/", priority: 0.7, changeFrequency: "weekly" as const },
    { url: "/actualizaciones-algoritmo-google-2026-que-ha-cambiado-y-como-afecta-tu-web/", priority: 0.7, changeFrequency: "weekly" as const },
    { url: "/seo-en-la-era-de-la-ia-como-posicionarse-cuando-google-usa-gemini/", priority: 0.7, changeFrequency: "weekly" as const },
    { url: "/linkedin-para-pymes-espanolas-en-2026-guia-practica-para-generar-leads/", priority: 0.7, changeFrequency: "weekly" as const },
    { url: "/redes-sociales-para-empresas-2026-que-funciona-de-verdad-segun-los-datos/", priority: 0.7, changeFrequency: "weekly" as const },
    { url: "/cuota-autonomos-2026-todo-lo-que-tienes-que-saber/", priority: 0.7, changeFrequency: "weekly" as const },
    { url: "/marketing-digital-para-autonomos-en-2026-como-conseguir-clientes-sin-agencia/", priority: 0.7, changeFrequency: "weekly" as const },
    { url: "/agentes-ia-marketing-que-son-como-usarlos-en-tu-negocio/", priority: 0.7, changeFrequency: "weekly" as const },
    { url: "/herramientas-ia-para-marketing-digital-2026-las-que-realmente-funcionan/", priority: 0.7, changeFrequency: "weekly" as const },
    { url: "/como-la-ia-esta-cambiando-el-marketing-digital-para-siempre/", priority: 0.7, changeFrequency: "weekly" as const },
    { url: "/que-es-un-chatbot-para-empresas-y-por-que-lo-necesitas-en-2026/", priority: 0.7, changeFrequency: "weekly" as const },
    { url: "/chatbot-para-tienda-online-guia-completa-2026/", priority: 0.7, changeFrequency: "weekly" as const },
    { url: "/chatbot-wordpress-como-instalarlo-que-evitar/", priority: 0.7, changeFrequency: "weekly" as const },
    { url: "/chatbot-ia-rgpd-ai-act-cumplimiento-legal-espana/", priority: 0.7, changeFrequency: "weekly" as const },
    { url: "/atencion-cliente-24-7-pymes-sin-contratar-personal/", priority: 0.7, changeFrequency: "weekly" as const },
    { url: "/chatbot-para-clinicas-centros-salud-automatizar-citas/", priority: 0.7, changeFrequency: "weekly" as const },
    { url: "/cuanto-cuesta-un-chatbot-para-empresas-espana-2026/", priority: 0.7, changeFrequency: "weekly" as const },
    { url: "/chatbot-captacion-cualificacion-leads-guia-practica/", priority: 0.7, changeFrequency: "weekly" as const },
    { url: "/chatbot-vs-live-chat-diferencias-cual-elegir-empresa/", priority: 0.7, changeFrequency: "weekly" as const },
    { url: "/como-elegir-chatbot-para-empresa-checklist-2026/", priority: 0.7, changeFrequency: "weekly" as const },
  ];

  return pages.map((p) => ({
    url: `${BASE}${p.url}`,
    lastModified: new Date(),
    changeFrequency: p.changeFrequency,
    priority: p.priority,
  }));
}
