import { MetadataRoute } from "next";

const BASE = "https://www.mktweb360.com";

export default function sitemap(): MetadataRoute.Sitemap {
  const pages = [
    { url: "/", priority: 1.0, changeFrequency: "weekly" as const },
    { url: "/seo-posicionamiento-web-organico/", priority: 0.9, changeFrequency: "monthly" as const },
    { url: "/sem-publicidad-ppc/", priority: 0.9, changeFrequency: "monthly" as const },
    { url: "/smm-social-media-marketing/", priority: 0.9, changeFrequency: "monthly" as const },
    { url: "/diseno-de-paginas-web/", priority: 0.9, changeFrequency: "monthly" as const },
    { url: "/diseno-de-paginas-web/paginas-corporativas/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/diseno-de-paginas-web/diseno-tiendas-online/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/diseno-de-paginas-web/diseno-paginas-web-empresa/", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/marketing-de-contenidos/", priority: 0.9, changeFrequency: "monthly" as const },
    { url: "/kit-digital/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/cuanto-cuesta-pagina-web-profesional/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/seo-o-google-ads-que-conviene-mas/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/seo-local-empresas-servicios/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/que-revisar-antes-de-invertir-mas-en-marketing-digital/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/senales-web-necesita-rediseno/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/como-generar-leads-calidad-pyme/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/seo-para-ecommerce-errores-que-frenan-ventas/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/que-puede-automatizar-una-pyme-en-marketing-y-ventas/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/ia-aplicada-a-marketing-valor-real-o-humo/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/como-puede-un-autonomo-conseguir-clientes-por-internet/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/nosotros/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/auditoria-digital/", priority: 0.9, changeFrequency: "monthly" as const },
    { url: "/comunicacion-audiovisual/", priority: 0.9, changeFrequency: "monthly" as const },
    { url: "/casos/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/blog/", priority: 0.8, changeFrequency: "weekly" as const },
    { url: "/oferta-web-seo/", priority: 0.9, changeFrequency: "monthly" as const },
    { url: "/contacto/", priority: 0.7, changeFrequency: "yearly" as const },
    { url: "/aviso-legal/", priority: 0.3, changeFrequency: "yearly" as const },
    { url: "/politica-de-privacidad/", priority: 0.3, changeFrequency: "yearly" as const },
    { url: "/politica-de-cookies/", priority: 0.3, changeFrequency: "yearly" as const },
    { url: "/seo-para-servicios-urgentes-24h/", priority: 0.6, changeFrequency: "yearly" as const },
    { url: "/como-crear-una-pagina-web-para-pintores-y-conseguir-clientes-en-google/", priority: 0.6, changeFrequency: "yearly" as const },
    { url: "/todo-lo-que-necesitas-saber-sobre-el-analisis-dafo-en-tu-estrategia-de-marketing/", priority: 0.6, changeFrequency: "yearly" as const },
    { url: "/descubre-el-poder-del-canvas-para-la-gestion-de-tus-redes-sociales/", priority: 0.6, changeFrequency: "yearly" as const },
    { url: "/descubre-el-analisis-pestel-en-el-marketing-digital/", priority: 0.6, changeFrequency: "yearly" as const },
    { url: "/como-elegir-el-mejor-hosting-para-tu-web/", priority: 0.6, changeFrequency: "yearly" as const },
    { url: "/ha-muerto-el-seo-con-la-ia/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/como-darse-de-alta-autonomo/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/factura-electronica-obligatoria-autonomos-pymes/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/como-digitalizar-tu-negocio/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/google-my-business-empresas-guia/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/como-crear-propuesta-de-valor/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/errores-digitales-negocio-nuevo/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/como-gestionar-reputacion-online-empresa/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/google-merchant-center-ecommerce-guia/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/google-business-profile/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/creacion-de-blog/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/whatsapp-marketing/", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/tienda-online/", priority: 0.9, changeFrequency: "monthly" as const },
  ];

  return pages.map((p) => ({
    url: `${BASE}${p.url}`,
    lastModified: new Date(),
    changeFrequency: p.changeFrequency,
    priority: p.priority,
  }));
}
