export type BlogPost = {
  slug: string;
  title: string;
  excerpt: string;
  date: string;
  category: string;
  tags: string[];
  relatedSlugs: string[];
};

export const allPosts: BlogPost[] = [
  { slug: "seo-para-servicios-urgentes-24h", title: "SEO para cerrajeros, fontaneros y electricistas 24h: más llamadas urgentes", excerpt: "El SEO bien ejecutado convierte tu web en un canal estable de captación para servicios urgentes.", date: "2025-01-15", category: "SEO", tags: ["seo-local","servicios","urgentes"], relatedSlugs: ["seo-local-empresas-servicios","seo-o-google-ads-que-conviene-mas"] },
  { slug: "como-crear-una-pagina-web-para-pintores-y-conseguir-clientes-en-google", title: "Cómo crear una página web para pintores y conseguir clientes en Google", excerpt: "Tu web de pintor no debería ser una tarjeta online. Debería captar clientes activamente.", date: "2025-02-01", category: "Diseño Web", tags: ["web","autonomos","local"], relatedSlugs: ["cuanto-cuesta-pagina-web-profesional","senales-web-necesita-rediseno"] },
  { slug: "todo-lo-que-necesitas-saber-sobre-el-analisis-dafo-en-tu-estrategia-de-marketing", title: "Todo lo que necesitas saber sobre el Análisis DAFO en tu Estrategia de Marketing", excerpt: "El análisis DAFO es una herramienta versátil para tomar decisiones informadas en marketing.", date: "2024-03-10", category: "Estrategia", tags: ["estrategia","analisis","pymes"], relatedSlugs: ["que-revisar-antes-de-invertir-mas-en-marketing-digital","como-generar-leads-calidad-pyme"] },
  { slug: "descubre-el-poder-del-canvas-para-la-gestion-de-tus-redes-sociales", title: "Descubre el Poder del Canvas para la Gestión de tus Redes Sociales", excerpt: "El Canvas es una herramienta fundamental para el éxito de tu estrategia en redes sociales.", date: "2024-03-17", category: "Social Media", tags: ["redes-sociales","estrategia","canvas"], relatedSlugs: ["que-revisar-antes-de-invertir-mas-en-marketing-digital","como-generar-leads-calidad-pyme"] },
  { slug: "descubre-el-analisis-pestel-en-el-marketing-digital", title: "Navegando el Entorno Digital: Descubre el Análisis PESTEL en el Marketing Digital", excerpt: "Un análisis PESTEL ayuda a comprender el entorno externo en el que opera tu organización.", date: "2024-03-24", category: "Estrategia", tags: ["estrategia","analisis","entorno"], relatedSlugs: ["todo-lo-que-necesitas-saber-sobre-el-analisis-dafo-en-tu-estrategia-de-marketing","que-revisar-antes-de-invertir-mas-en-marketing-digital"] },
  { slug: "como-elegir-el-mejor-hosting-para-tu-web", title: "Cómo elegir el mejor hosting para tu web", excerpt: "La elección de un buen hosting garantiza velocidad y rendimiento. Te mostramos las claves.", date: "2022-06-01", category: "Diseño Web", tags: ["web","hosting","tecnico"], relatedSlugs: ["cuanto-cuesta-pagina-web-profesional","senales-web-necesita-rediseno"] },
  { slug: "cuanto-cuesta-pagina-web-profesional", title: "Cuánto cuesta una página web profesional y qué debe incluir para generar clientes", excerpt: "Descubre qué influye en el precio de una web profesional y qué debe incluir para captar clientes.", date: "2025-03-10", category: "Diseño Web", tags: ["web","precio","presupuesto","pymes"], relatedSlugs: ["senales-web-necesita-rediseno","seo-o-google-ads-que-conviene-mas"] },
  { slug: "seo-o-google-ads-que-conviene-mas", title: "SEO o Google Ads: qué conviene más según tu negocio, presupuesto y urgencia", excerpt: "Descubre si te conviene más SEO, Google Ads o una combinación según tu negocio y urgencia.", date: "2025-03-17", category: "SEO", tags: ["seo","sem","google-ads","captacion"], relatedSlugs: ["seo-local-empresas-servicios","que-revisar-antes-de-invertir-mas-en-marketing-digital"] },
  { slug: "seo-local-empresas-servicios", title: "SEO local para empresas de servicios: cómo conseguir clientes en tu zona", excerpt: "Aprende qué necesita una empresa de servicios para mejorar su presencia local en Google.", date: "2025-03-24", category: "SEO", tags: ["seo-local","servicios","captacion","google-maps"], relatedSlugs: ["como-puede-un-autonomo-conseguir-clientes-por-internet","seo-o-google-ads-que-conviene-mas"] },
  { slug: "que-revisar-antes-de-invertir-mas-en-marketing-digital", title: "Qué revisar en tu empresa antes de invertir más en marketing digital", excerpt: "Revisa estas 7 áreas clave antes de invertir más en marketing para no amplificar errores.", date: "2025-04-01", category: "Estrategia", tags: ["auditoria","estrategia","pymes","inversion"], relatedSlugs: ["seo-o-google-ads-que-conviene-mas","como-generar-leads-calidad-pyme"] },
  { slug: "senales-web-necesita-rediseno", title: "Señales de que tu web necesita un rediseño urgente si quieres vender más", excerpt: "Descubre las señales más claras de que tu web está frenando ventas y cuándo conviene rediseñar.", date: "2025-04-07", category: "Diseño Web", tags: ["web","rediseno","conversion","ux"], relatedSlugs: ["cuanto-cuesta-pagina-web-profesional","como-generar-leads-calidad-pyme"] },
  { slug: "como-generar-leads-calidad-pyme", title: "Cómo generar leads de calidad para una pyme sin llenar el embudo de contactos inútiles", excerpt: "Aprende cómo mejorar mensaje, segmentación, canales y proceso comercial para captar mejor.", date: "2025-04-14", category: "Captación", tags: ["leads","captacion","pymes","conversion"], relatedSlugs: ["seo-o-google-ads-que-conviene-mas","que-puede-automatizar-una-pyme-en-marketing-y-ventas"] },
  { slug: "seo-para-ecommerce-errores-que-frenan-ventas", title: "SEO para ecommerce: los errores que más frenan ventas en una tienda online", excerpt: "Descubre los errores SEO más comunes en ecommerce y cómo mejorar visibilidad y ventas.", date: "2025-04-21", category: "Ecommerce", tags: ["ecommerce","seo","tienda-online","ventas"], relatedSlugs: ["senales-web-necesita-rediseno","que-revisar-antes-de-invertir-mas-en-marketing-digital"] },
  { slug: "que-puede-automatizar-una-pyme-en-marketing-y-ventas", title: "Qué puede automatizar una pyme en marketing y ventas para ahorrar tiempo y captar mejor", excerpt: "Descubre qué procesos conviene automatizar para ahorrar tiempo y mejorar el seguimiento.", date: "2025-04-28", category: "Automatización", tags: ["automatizacion","pymes","marketing","ventas"], relatedSlugs: ["ia-aplicada-a-marketing-valor-real-o-humo","como-generar-leads-calidad-pyme"] },
  { slug: "ia-aplicada-a-marketing-valor-real-o-humo", title: "IA aplicada a marketing: dónde aporta valor real y dónde sigue siendo humo", excerpt: "Separa el ruido de la señal: dónde la IA aporta valor real en marketing y dónde no.", date: "2025-05-01", category: "IA", tags: ["ia","marketing","automatizacion","tendencias"], relatedSlugs: ["que-puede-automatizar-una-pyme-en-marketing-y-ventas","que-revisar-antes-de-invertir-mas-en-marketing-digital"] },
  { slug: "como-puede-un-autonomo-conseguir-clientes-por-internet", title: "Cómo puede un autónomo conseguir clientes por Internet sin depender solo del boca a boca", excerpt: "Construye una base digital clara y rentable para conseguir clientes de forma estable.", date: "2025-05-05", category: "Autónomos", tags: ["autonomos","seo-local","web","captacion"], relatedSlugs: ["seo-local-empresas-servicios","cuanto-cuesta-pagina-web-profesional"] },
  { slug: "ejemplos-y-diferencias-entre-buscadores-y-navegadores", title: "Diferencias entre buscadores y navegadores: ejemplos y guía completa", excerpt: "Descubre las diferencias clave entre navegadores y buscadores con ejemplos reales de Chrome, Firefox, Google o Bing.", date: "2025-06-12", category: "SEO", tags: ["seo","navegadores","buscadores","google"], relatedSlugs: ["seo-o-google-ads-que-conviene-mas","seo-posicionamiento-web-organico"] },
  { slug: "instagram-para-empresas-que-poner-en-la-biografia-de-instagram", title: "Qué poner en la biografía de Instagram para empresas: guía completa con ejemplos", excerpt: "La biografía de Instagram es tu tarjeta de presentación. Tienes 150 caracteres para convencer. Te explicamos cómo usarlos.", date: "2025-06-12", category: "Social Media", tags: ["instagram","redes-sociales","empresa"], relatedSlugs: ["descubre-el-poder-del-canvas-para-la-gestion-de-tus-redes-sociales","que-puede-automatizar-una-pyme-en-marketing-y-ventas"] },
  { slug: "ha-muerto-el-seo-con-la-ia", title: "¿Ha muerto el SEO con la IA? La analogía del Ferrari y Fernando Alonso", excerpt: "Muchos creen que la IA ha matado el SEO. Analizamos por qué eso no es cierto y por qué IA + técnico cualificado es la fórmula ganadora.", date: "2026-06-12", category: "SEO", tags: ["seo","ia","marketing","tendencias"], relatedSlugs: ["ia-aplicada-a-marketing-valor-real-o-humo","seo-o-google-ads-que-conviene-mas"] },
  { slug: "como-darse-de-alta-autonomo", title: "Cómo darse de alta como autónomo en 2026: pasos, costes y errores a evitar", excerpt: "Guía completa para darse de alta como autónomo en 2026. Pasos en Hacienda y Seguridad Social, cuota, errores frecuentes y qué necesitas tener listo.", date: "2026-06-12", category: "Autónomos", tags: ["autonomos","alta","hacienda","seguridad-social"], relatedSlugs: ["como-puede-un-autonomo-conseguir-clientes-por-internet","errores-digitales-negocio-nuevo"] },
  { slug: "factura-electronica-obligatoria-autonomos-pymes", title: "Factura electrónica obligatoria para autónomos y pymes: qué debes saber en 2026", excerpt: "La factura electrónica será obligatoria para autónomos y pymes. Descubre qué implica, cuándo entra en vigor, qué necesitas y cómo prepararte.", date: "2026-06-12", category: "Autónomos", tags: ["autonomos","factura-electronica","digitalizacion","ley-crea-y-crece"], relatedSlugs: ["como-digitalizar-tu-negocio","que-revisar-antes-de-invertir-mas-en-marketing-digital"] },
  { slug: "como-digitalizar-tu-negocio", title: "Cómo digitalizar tu negocio sin complicarte la vida: guía práctica para pymes en 2026", excerpt: "Digitalizar un negocio no significa comprar software caro. Descubre qué pasos dar primero, qué herramientas tienen sentido y cómo hacerlo con orden.", date: "2026-06-12", category: "Pymes", tags: ["digitalizacion","pymes","herramientas","kit-digital"], relatedSlugs: ["errores-digitales-negocio-nuevo","que-revisar-antes-de-invertir-mas-en-marketing-digital"] },
  { slug: "google-my-business-empresas-guia", title: "Google Business Profile para empresas: guía completa 2026", excerpt: "Aprende a optimizar tu ficha de Google Business Profile para aparecer en búsquedas locales, conseguir más reseñas y convertir visitas en clientes.", date: "2026-06-12", category: "SEO Local", tags: ["seo-local","google-business-profile","resenas","captacion"], relatedSlugs: ["seo-local-empresas-servicios","como-puede-un-autonomo-conseguir-clientes-por-internet"] },
  { slug: "como-crear-propuesta-de-valor", title: "Cómo crear una propuesta de valor que atraiga a los clientes que quieres", excerpt: "Una propuesta de valor clara es la base de cualquier estrategia de marketing efectiva. Aprende a construirla con ejemplos prácticos para pymes.", date: "2026-06-12", category: "Estrategia", tags: ["estrategia","propuesta-de-valor","pymes","conversion"], relatedSlugs: ["como-generar-leads-calidad-pyme","errores-digitales-negocio-nuevo"] },
  { slug: "errores-digitales-negocio-nuevo", title: "10 errores digitales al montar un negocio desde cero (y cómo evitarlos)", excerpt: "Arrancar un negocio con errores digitales cuesta dinero y tiempo. Descubre los más frecuentes y cómo evitarlos desde el principio.", date: "2026-06-12", category: "Emprendedores", tags: ["emprendedores","web","seo","errores"], relatedSlugs: ["como-darse-de-alta-autonomo","como-digitalizar-tu-negocio"] },
  { slug: "como-gestionar-reputacion-online-empresa", title: "Cómo gestionar la reputación online de tu empresa: guía práctica 2026", excerpt: "La reputación online se construye o destruye en público. Descubre cómo gestionarla con criterio: reseñas, menciones, respuestas y prevención de crisis.", date: "2026-06-12", category: "Estrategia", tags: ["reputacion-online","resenas","google","estrategia"], relatedSlugs: ["google-my-business-empresas-guia","como-crear-propuesta-de-valor"] },
  { slug: "google-merchant-center-ecommerce-guia", title: "Google Merchant Center para ecommerce: guía completa 2026", excerpt: "Aprende a configurar Google Merchant Center, crear tu feed de productos y aparecer en Google Shopping para aumentar las ventas de tu tienda online.", date: "2026-06-12", category: "Ecommerce", tags: ["ecommerce","google-shopping","merchant-center","google-ads"], relatedSlugs: ["seo-para-ecommerce-errores-que-frenan-ventas","senales-web-necesita-rediseno"] },
];

export function getLatestPosts(n: number): BlogPost[] {
  return [...allPosts].sort((a, b) => b.date.localeCompare(a.date)).slice(0, n);
}

export function getRelatedPosts(currentSlug: string, n: number): BlogPost[] {
  const current = allPosts.find(p => p.slug === currentSlug);
  if (!current) return getLatestPosts(n);
  const byRelated = allPosts.filter(p => current.relatedSlugs.includes(p.slug));
  if (byRelated.length >= n) return byRelated.slice(0, n);
  const byTag = allPosts.filter(p => p.slug !== currentSlug && !current.relatedSlugs.includes(p.slug) && p.tags.some(t => current.tags.includes(t)));
  return [...byRelated, ...byTag].slice(0, n);
}

export function getPostsByCategory(category: string, n: number): BlogPost[] {
  return allPosts.filter(p => p.category.toLowerCase().includes(category.toLowerCase())).slice(0, n).concat(getLatestPosts(n)).filter((v,i,a)=>a.findIndex(p=>p.slug===v.slug)===i).slice(0,n);
}
