export type BlogPost = {
  slug: string;
  title: string;
  excerpt: string;
  date: string;
  category: string;
  tags: string[];
  relatedSlugs: string[];
};

export const allPosts: BlogPost[] = [
  { slug: 'cuando-elegir-seo-vs-google-ads', title: 'Cuándo elegir SEO y cuándo Google Ads: guía para tomar la decisión correcta según tu negocio', excerpt: 'SEO o Google Ads: aprende cuándo invertir en posicionamiento orgánico y cuándo en publicidad de pago según tu situación, sector y objetivos de negocio.', date: '2026-02-23', category: 'SEO', tags: ['seo', 'google ads', 'estrategia', 'sem'], relatedSlugs: ['seo-posicionamiento-web-organico', 'sem-publicidad-ppc', 'auditoria-seo-basica'] },
  { slug: 'geo-vs-seo-diferencias', title: 'GEO vs SEO: diferencias clave y cómo compaginar ambas estrategias en 2025', excerpt: 'GEO y SEO no son lo mismo. Descubre qué diferencia el posicionamiento en buscadores del posicionamiento en IA y cómo usar ambas estrategias juntas.', date: '2026-02-09', category: 'GEO', tags: ['geo', 'seo', 'ia', 'estrategia'], relatedSlugs: ['geo-posicionamiento-ia', 'que-es-geo-generative-engine-optimization', 'seo-posicionamiento-web-organico'] },
  { slug: 'configurar-envios-woocommerce', title: 'Cómo configurar los envíos en WooCommerce para España: guía completa paso a paso', excerpt: 'Configura los métodos de envío en WooCommerce correctamente: zonas de envío, transportistas, envío gratis y tarifas por peso para tu tienda online en España.', date: '2026-01-26', category: 'Ecommerce', tags: ['woocommerce', 'envíos', 'tienda online', 'ecommerce'], relatedSlugs: ['diseno-de-paginas-web/diseno-tiendas-online', 'metodos-pago-tienda-online-espana', 'importar-productos-woocommerce'] },
  { slug: 'link-building-pymes', title: 'Link building para PYMEs: cómo conseguir backlinks de calidad sin presupuesto para spam', excerpt: 'Estrategias de link building accesibles para pymes y autónomos: cómo conseguir enlaces de calidad que mejoren tu autoridad de dominio sin riesgos.', date: '2026-01-12', category: 'SEO', tags: ['link building', 'seo', 'backlinks', 'pymes'], relatedSlugs: ['seo-posicionamiento-web-organico', 'auditoria-seo-basica', 'cuando-elegir-seo-vs-google-ads'] },
  { slug: 'google-shopping-tiendas-online', title: 'Google Shopping para tiendas online: cómo aparecer en los resultados de compra y aumentar ventas', excerpt: 'Aprende a configurar Google Shopping para tu tienda online: feed de productos, Google Merchant Center y campañas de Shopping para aumentar tus ventas.', date: '2025-12-22', category: 'Ecommerce', tags: ['google shopping', 'ecommerce', 'google ads', 'tienda online'], relatedSlugs: ['sem-publicidad-ppc', 'diseno-de-paginas-web/diseno-tiendas-online', 'metodos-pago-tienda-online-espana'] },
  { slug: 'chatgpt-para-marketing-digital', title: 'Cómo usar ChatGPT para marketing digital sin perder la autenticidad de tu marca', excerpt: 'Guía práctica para usar ChatGPT en marketing digital: qué tareas puedes delegar a la IA y cuáles debes mantener humanas para no perder tu voz de marca.', date: '2025-12-08', category: 'IA y Automatización', tags: ['chatgpt', 'ia', 'marketing digital', 'automatización'], relatedSlugs: ['ia-aplicada-al-marketing', 'geo-posicionamiento-ia', 'agentes-ia-marketing-que-son-como-usarlos-en-tu-negocio'] },
  { slug: 'auditoria-seo-basica', title: 'Cómo hacer una auditoría SEO básica de tu web: guía práctica sin conocimientos técnicos', excerpt: 'Aprende a hacer una auditoría SEO básica de tu web paso a paso: errores técnicos, contenido, keywords y backlinks. Sin herramientas de pago ni conocimientos avanzados.', date: '2025-12-01', category: 'SEO', tags: ['auditoría seo', 'seo', 'seo técnico', 'pymes'], relatedSlugs: ['seo-posicionamiento-web-organico', 'link-building-pymes', 'cuando-elegir-seo-vs-google-ads'] },
  { slug: 'metodos-pago-tienda-online-espana', title: 'Métodos de pago para tiendas online en España: cuál elegir y cuánto cobran en 2025', excerpt: 'Comparativa de los mejores métodos de pago para tiendas online en España: Stripe, PayPal, Bizum, Redsys y aplazamiento. Comisiones, integración y cuál conviene más.', date: '2025-11-17', category: 'Ecommerce', tags: ['métodos de pago', 'tienda online', 'ecommerce', 'stripe'], relatedSlugs: ['diseno-de-paginas-web/diseno-tiendas-online', 'configurar-envios-woocommerce', 'migrar-shopify-woocommerce'] },
  { slug: 'migrar-shopify-woocommerce', title: 'Cómo migrar de Shopify a WooCommerce sin perder tu tienda ni tu posicionamiento', excerpt: 'Guía completa para migrar de Shopify a WooCommerce: productos, clientes, pedidos, SEO y redirecciones. Sin perder datos ni posiciones en Google.', date: '2025-11-03', category: 'Ecommerce', tags: ['shopify', 'woocommerce', 'migración', 'ecommerce'], relatedSlugs: ['migrar-tienda-online-sin-perder-datos', 'diseno-de-paginas-web/diseno-tiendas-online', 'seo-posicionamiento-web-organico'] },
  { slug: 'migrar-tienda-online-sin-perder-datos', title: 'Cómo migrar tu tienda online sin perder datos, pedidos ni posicionamiento en Google', excerpt: 'Todo lo que necesitas saber para migrar tu tienda online de plataforma sin perder datos, historial de pedidos, clientes ni posicionamiento orgánico.', date: '2025-10-20', category: 'Ecommerce', tags: ['migración ecommerce', 'tienda online', 'seo', 'woocommerce'], relatedSlugs: ['migrar-shopify-woocommerce', 'diseno-de-paginas-web/diseno-tiendas-online', 'configurar-envios-woocommerce'] },
  { slug: 'conectar-tpv-tienda-online', title: 'Cómo conectar el TPV de tu tienda física con tu tienda online: guía completa', excerpt: 'Aprende a sincronizar tu punto de venta físico con tu tienda online: stock unificado, pedidos centralizados y gestión simplificada para negocios omnicanal.', date: '2025-10-13', category: 'Ecommerce', tags: ['tpv', 'tienda online', 'omnicanal', 'ecommerce'], relatedSlugs: ['diseno-de-paginas-web/diseno-tiendas-online', 'metodos-pago-tienda-online-espana', 'configurar-envios-woocommerce'] },
  { slug: 'importar-productos-woocommerce', title: 'Cómo importar productos en WooCommerce con CSV: guía paso a paso sin errores', excerpt: 'Importa productos masivamente en WooCommerce usando archivos CSV: formato correcto, campos obligatorios, imágenes y solución de errores comunes.', date: '2025-10-06', category: 'Ecommerce', tags: ['woocommerce', 'importar productos', 'csv', 'ecommerce'], relatedSlugs: ['migrar-shopify-woocommerce', 'diseno-de-paginas-web/diseno-tiendas-online', 'configurar-envios-woocommerce'] },
  { slug: 'gestion-resenas-negativas-google', title: 'Cómo gestionar las reseñas negativas en Google sin perder clientes', excerpt: 'Aprende a responder reseñas negativas en Google de forma profesional, cuándo solicitar su eliminación y cómo convertir una crítica en una oportunidad.', date: '2025-08-25', category: 'Marketing Digital', tags: ['reseñas google', 'reputación online', 'google business profile', 'atención al cliente'], relatedSlugs: ['reputacion-online', 'google-my-business-empresas-guia', 'seo-local-empresas-servicios'] },
  { slug: 'como-medir-roi-marketing-digital', title: 'Cómo medir el ROI de tus campañas de marketing digital paso a paso', excerpt: 'Aprende a calcular el ROI de tus acciones de marketing digital: fórmulas, métricas clave por canal y cómo interpretar los datos para tomar mejores decisiones.', date: '2025-08-18', category: 'Marketing Digital', tags: ['roi', 'analítica', 'marketing digital', 'métricas'], relatedSlugs: ['analitica-web', 'sem-publicidad-ppc', 'seo-posicionamiento-web-organico'] },
  { slug: 'email-marketing-pymes', title: 'Email marketing para PYMEs: guía de primeros pasos para empezar a vender por email', excerpt: 'Cómo empezar con el email marketing si eres una pyme o autónomo: herramientas, primeras listas, tipos de emails y métricas que importan.', date: '2025-08-11', category: 'Marketing Digital', tags: ['email marketing', 'pymes', 'newsletter', 'marketing digital'], relatedSlugs: ['marketing-de-contenidos', 'como-generar-leads-calidad-pyme', 'como-crear-landing-page-que-convierte'] },
  { slug: 'whatsapp-business-para-empresas', title: 'WhatsApp Business para empresas: guía completa de configuración y estrategia', excerpt: 'Todo lo que necesitas saber para usar WhatsApp Business en tu empresa: configuración, catálogo, etiquetas, respuestas automáticas y estrategia de captación.', date: '2025-08-04', category: 'Marketing Digital', tags: ['whatsapp business', 'marketing digital', 'atención al cliente', 'pymes'], relatedSlugs: ['smm-social-media-marketing', 'marketing-de-contenidos', 'como-generar-leads-calidad-pyme'] },
  { slug: 'como-crear-landing-page-que-convierte', title: 'Cómo crear una landing page que convierte visitas en clientes', excerpt: 'Guía práctica para crear landing pages de alta conversión: estructura, copywriting, CTA, formularios y errores más comunes que destruyen la tasa de conversión.', date: '2025-07-28', category: 'Diseño Web', tags: ['landing page', 'conversión', 'diseño web', 'copywriting'], relatedSlugs: ['diseno-de-paginas-web', 'sem-publicidad-ppc', 'como-medir-roi-marketing-digital'] },
  { slug: 'que-es-geo-generative-engine-optimization', title: 'Qué es el GEO y por qué es más importante que el SEO tradicional en 2025', excerpt: 'Descubre qué es el GEO (Generative Engine Optimization), cómo funciona y por qué optimizar tu presencia para ChatGPT, Gemini y Perplexity es clave en 2025.', date: '2025-07-21', category: 'GEO', tags: ['geo', 'ia', 'seo', 'chatgpt'], relatedSlugs: ['geo-posicionamiento-ia', 'geo-vs-seo-diferencias', 'seo-posicionamiento-web-organico'] },
  { slug: 'digitalizacion-empresas-castilla-la-mancha', title: 'Cómo digitalizar tu empresa en Castilla-La Mancha en 2025', excerpt: 'Guía práctica para digitalizar tu empresa en Castilla-La Mancha: herramientas, pasos, ayudas disponibles y estrategia digital adaptada al mercado regional.', date: '2025-06-16', category: 'Marketing Digital', tags: ['digitalización', 'castilla la mancha', 'pymes', 'estrategia digital'], relatedSlugs: ['seo-posicionamiento-web-organico', 'diseno-de-paginas-web', 'marketing-digital-toledo'] },
  { slug: "seo-para-servicios-urgentes-24h", title: "SEO para cerrajeros, fontaneros y electricistas 24h: más llamadas urgentes", excerpt: "El SEO bien ejecutado convierte tu web en un canal estable de captación para servicios urgentes.", date: "2025-01-15", category: "SEO", tags: ["seo-local","servicios","urgentes"], relatedSlugs: ["seo-local-empresas-servicios","seo-o-google-ads-que-conviene-mas"] },
  { slug: "como-crear-una-pagina-web-para-pintores-y-conseguir-clientes-en-google", title: "Cómo crear una página web para pintores y conseguir clientes en Google", excerpt: "Tu web de pintor no debería ser una tarjeta online. Debería captar clientes activamente.", date: "2025-02-01", category: "Diseño Web", tags: ["web","autonomos","local"], relatedSlugs: ["cuanto-cuesta-pagina-web-profesional","senales-web-necesita-rediseno"] },
  { slug: "todo-lo-que-necesitas-saber-sobre-el-analisis-dafo-en-tu-estrategia-de-marketing", title: "Todo lo que necesitas saber sobre el Análisis DAFO en tu Estrategia de Marketing", excerpt: "El análisis DAFO es una herramienta versátil para tomar decisiones informadas en marketing.", date: "2024-03-10", category: "Estrategia", tags: ["estrategia","analisis","pymes"], relatedSlugs: ["que-revisar-antes-de-invertir-mas-en-marketing-digital","como-generar-leads-calidad-pyme"] },
  { slug: "descubre-el-poder-del-canvas-para-la-gestion-de-tus-redes-sociales", title: "Descubre el Poder del Canvas para la Gestión de tus Redes Sociales", excerpt: "El Canvas es una herramienta fundamental para el éxito de tu estrategia en redes sociales.", date: "2024-03-17", category: "Social Media", tags: ["redes-sociales","estrategia","canvas"], relatedSlugs: ["que-revisar-antes-de-invertir-mas-en-marketing-digital","como-generar-leads-calidad-pyme"] },
  { slug: "descubre-el-analisis-pestel-en-el-marketing-digital", title: "Navegando el Entorno Digital: Descubre el Análisis PESTEL en el Marketing Digital", excerpt: "Un análisis PESTEL ayuda a comprender el entorno externo en el que opera tu organización.", date: "2024-03-24", category: "Estrategia", tags: ["estrategia","analisis","entorno"], relatedSlugs: ["todo-lo-que-necesitas-saber-sobre-el-analisis-dafo-en-tu-estrategia-de-marketing","que-revisar-antes-de-invertir-mas-en-marketing-digital"] },
  { slug: "como-elegir-el-mejor-hosting-para-tu-web", title: "Cómo elegir el mejor hosting para tu web", excerpt: "La elección de un buen hosting garantiza velocidad y rendimiento. Te mostramos las claves.", date: "2022-06-01", category: "Diseño Web", tags: ["web","hosting","tecnico"], relatedSlugs: ["cuanto-cuesta-pagina-web-profesional","senales-web-necesita-rediseno"] },
  { slug: "cuanto-cuesta-pagina-web-profesional", title: "Cuánto cuesta una página web profesional y qué debe incluir para generar clientes", excerpt: "Descubre qué influye en el precio de una web profesional y qué debe incluir para captar clientes.", date: "2025-03-10", category: "Diseño Web", tags: ["web","precio","presupuesto","pymes"], relatedSlugs: ["senales-web-necesita-rediseno","seo-o-google-ads-que-conviene-mas"] },
  { slug: "seo-o-google-ads-que-conviene-mas", title: "SEO o Google Ads: qué conviene más según tu negocio, presupuesto y urgencia", excerpt: "Descubre si te conviene más SEO, Google Ads o una combinación según tu negocio y urgencia.", date: "2025-03-17", category: "SEO", tags: ["seo","sem","google-ads","captacion"], relatedSlugs: ["seo-local-empresas-servicios","que-revisar-antes-de-invertir-mas-en-marketing-digital"] },
  { slug: "seo-local-empresas-servicios", title: "SEO local para empresas de servicios: cómo conseguir clientes en tu zona", excerpt: "Aprende qué necesita una empresa de servicios para mejorar su presencia local en Google.", date: "2025-03-24", category: "SEO", tags: ["seo-local","servicios","captacion","google-maps"], relatedSlugs: ["como-puede-un-autonomo-conseguir-clientes-por-internet","seo-o-google-ads-que-conviene-mas"] },
  { slug: "que-revisar-antes-de-invertir-mas-en-marketing-digital", title: "Qué revisar en tu empresa antes de invertir más en marketing digital", excerpt: "Revisa estas 7 áreas clave antes de invertir más en marketing para no amplificar errores.", date: "2025-04-01", category: "Estrategia", tags: ["auditoria","estrategia","pymes","inversion"], relatedSlugs: ["seo-o-google-ads-que-conviene-mas","como-generar-leads-calidad-pyme"] },
  { slug: "senales-web-necesita-rediseno", title: "Señales de que tu web necesita un rediseño urgente si quieres vender más", excerpt: "Descubre las señales más claras de que tu web está frenando ventas y cuándo conviene rediseñar.", date: "2025-04-07", category: "Diseño Web", tags: ["web","rediseno","conversion","ux"], relatedSlugs: ["cuanto-cuesta-pagina-web-profesional","como-generar-leads-calidad-pyme"] },
  { slug: "como-generar-leads-calidad-pyme", title: "Cómo generar leads de calidad para una pyme sin llenar el embudo de contactos inútiles", excerpt: "Aprende cómo mejorar mensaje, segmentación, canales y proceso comercial para captar mejor.", date: "2025-04-14", category: "Captación", tags: ["leads","captacion","pymes","conversion"], relatedSlugs: ["seo-o-google-ads-que-conviene-mas","que-puede-automatizar-una-pyme-en-marketing-y-ventas"] },
  { slug: "seo-para-ecommerce-errores-que-frenan-ventas", title: "SEO para ecommerce: los errores que más frenan ventas en una tienda online", excerpt: "Descubre los errores SEO más comunes en ecommerce y cómo mejorar visibilidad y ventas.", date: "2025-04-21", category: "Ecommerce", tags: ["ecommerce","seo","tienda-online","ventas"], relatedSlugs: ["senales-web-necesita-rediseno","que-revisar-antes-de-invertir-mas-en-marketing-digital"] },
  { slug: "que-puede-automatizar-una-pyme-en-marketing-y-ventas", title: "Qué puede automatizar una pyme en marketing y ventas para ahorrar tiempo y captar mejor", excerpt: "Descubre qué procesos conviene automatizar para ahorrar tiempo y mejorar el seguimiento.", date: "2025-04-28", category: "Automatización", tags: ["automatizacion","pymes","marketing","ventas"], relatedSlugs: ["ia-aplicada-a-marketing-valor-real-o-humo","como-generar-leads-calidad-pyme"] },
  { slug: "ia-aplicada-a-marketing-valor-real-o-humo", title: "IA aplicada a marketing: dónde aporta valor real y dónde sigue siendo humo", excerpt: "Separa el ruido de la señal: dónde la IA aporta valor real en marketing y dónde no.", date: "2025-05-01", category: "IA", tags: ["ia","marketing","automatizacion","tendencias"], relatedSlugs: ["que-puede-automatizar-una-pyme-en-marketing-y-ventas","que-revisar-antes-de-invertir-mas-en-marketing-digital"] },
  { slug: "como-puede-un-autonomo-conseguir-clientes-por-internet", title: "Cómo puede un autónomo conseguir clientes por Internet sin depender solo del boca a boca", excerpt: "Construye una base digital clara y rentable para conseguir clientes de forma estable.", date: "2025-05-05", category: "Autónomos", tags: ["autonomos","seo-local","web","captacion"], relatedSlugs: ["seo-local-empresas-servicios","cuanto-cuesta-pagina-web-profesional"] },
  { slug: "ejemplos-y-diferencias-entre-buscadores-y-navegadores", title: "Diferencias entre buscadores y navegadores: ejemplos y guía completa", excerpt: "Descubre las diferencias clave entre navegadores y buscadores con ejemplos reales de Chrome, Firefox, Google o Bing.", date: "2025-06-12", category: "SEO", tags: ["seo","navegadores","buscadores","google"], relatedSlugs: ["seo-o-google-ads-que-conviene-mas","seo-posicionamiento-web-organico"] },
  { slug: "instagram-para-empresas-que-poner-en-la-biografia-de-instagram", title: "Qué poner en la biografía de Instagram para empresas: guía completa con ejemplos", excerpt: "La biografía de Instagram es tu tarjeta de presentación. Tienes 150 caracteres para convencer. Te explicamos cómo usarlos.", date: "2025-06-12", category: "Social Media", tags: ["instagram","redes-sociales","empresa"], relatedSlugs: ["descubre-el-poder-del-canvas-para-la-gestion-de-tus-redes-sociales","que-puede-automatizar-una-pyme-en-marketing-y-ventas"] },
  { slug: "ha-muerto-el-seo-con-la-ia", title: "¿Ha muerto el SEO con la IA? La analogía del Ferrari y Fernando Alonso", excerpt: "Muchos creen que la IA ha matado el SEO. Analizamos por qué eso no es cierto y por qué IA + técnico cualificado es la fórmula ganadora.", date: "2026-06-12", category: "SEO", tags: ["seo","ia","marketing","tendencias"], relatedSlugs: ["ia-aplicada-a-marketing-valor-real-o-humo","seo-o-google-ads-que-conviene-mas"] },
  { slug: "como-darse-de-alta-autonomo", title: "Cómo darse de alta como autónomo en 2026: pasos, costes y errores a evitar", excerpt: "Guía completa para darse de alta como autónomo en 2026. Pasos en Hacienda y Seguridad Social, cuota, errores frecuentes y qué necesitas tener listo.", date: "2026-06-12", category: "Autónomos", tags: ["autonomos","alta","hacienda","seguridad-social"], relatedSlugs: ["como-puede-un-autonomo-conseguir-clientes-por-internet","errores-digitales-negocio-nuevo"] },
  { slug: "factura-electronica-obligatoria-autonomos-pymes", title: "Factura electrónica obligatoria para autónomos y pymes: qué debes saber en 2026", excerpt: "La factura electrónica será obligatoria para autónomos y pymes. Descubre qué implica, cuándo entra en vigor, qué necesitas y cómo prepararte.", date: "2026-06-12", category: "Autónomos", tags: ["autonomos","factura-electronica","digitalizacion","ley-crea-y-crece"], relatedSlugs: ["como-digitalizar-tu-negocio","que-revisar-antes-de-invertir-mas-en-marketing-digital"] },
  { slug: "como-digitalizar-tu-negocio", title: "Cómo digitalizar tu negocio sin complicarte la vida: guía práctica para pymes en 2026", excerpt: "Digitalizar un negocio no significa comprar software caro. Descubre qué pasos dar primero, qué herramientas tienen sentido y cómo hacerlo con orden.", date: "2026-06-12", category: "Pymes", tags: ["digitalizacion","pymes","herramientas","kit-digital"], relatedSlugs: ["errores-digitales-negocio-nuevo","que-revisar-antes-de-invertir-mas-en-marketing-digital"] },
  { slug: "google-my-business-empresas-guia", title: "Google Business Profile para empresas: guía completa 2026", excerpt: "Aprende a optimizar tu ficha de Google Business Profile para aparecer en búsquedas locales, conseguir más reseñas y convertir visitas en clientes.", date: "2026-06-12", category: "SEO Local", tags: ["seo-local","google-business-profile","resenas","captacion"], relatedSlugs: ["seo-local-empresas-servicios","como-puede-un-autonomo-conseguir-clientes-por-internet"] },
  { slug: "como-crear-propuesta-de-valor", title: "Cómo crear una propuesta de valor que atraiga a los clientes que quieres", excerpt: "Una propuesta de valor clara es la base de cualquier estrategia de marketing efectiva. Aprende a construirla con ejemplos prácticos para pymes.", date: "2026-06-12", category: "Estrategia", tags: ["estrategia","propuesta-de-valor","pymes","conversion"], relatedSlugs: ["como-generar-leads-calidad-pyme","errores-digitales-negocio-nuevo"] },
  { slug: "errores-digitales-negocio-nuevo", title: "10 errores digitales al montar un negocio desde cero (y cómo evitarlos)", excerpt: "Arrancar un negocio con errores digitales cuesta dinero y tiempo. Descubre los más frecuentes y cómo evitarlos desde el principio.", date: "2026-06-12", category: "Emprendedores", tags: ["emprendedores","web","seo","errores"], relatedSlugs: ["como-darse-de-alta-autonomo","como-digitalizar-tu-negocio"] },
  { slug: "como-gestionar-reputacion-online-empresa", title: "Cómo gestionar la reputación online de tu empresa: guía práctica 2026", excerpt: "La reputación online se construye o destruye en público. Descubre cómo gestionarla con criterio: reseñas, menciones, respuestas y prevención de crisis.", date: "2026-06-12", category: "Estrategia", tags: ["reputacion-online","resenas","google","estrategia"], relatedSlugs: ["google-my-business-empresas-guia","como-crear-propuesta-de-valor"] },
  { slug: "google-merchant-center-ecommerce-guia", title: "Google Merchant Center para ecommerce: guía completa 2026", excerpt: "Aprende a configurar Google Merchant Center, crear tu feed de productos y aparecer en Google Shopping para aumentar las ventas de tu tienda online.", date: "2026-06-12", category: "Ecommerce", tags: ["ecommerce","google-shopping","merchant-center","google-ads"], relatedSlugs: ["seo-para-ecommerce-errores-que-frenan-ventas","senales-web-necesita-rediseno"] },
  { slug: "geo-posicionamiento-ia-chatgpt-empresas-espana", title: "Qué es el GEO y cómo aparecer en ChatGPT si tienes un negocio en España", excerpt: "El GEO posiciona tu negocio en ChatGPT y Perplexity. Si la IA no te menciona cuando alguien pregunta por tu sector, pierdes clientes. Guía práctica para negocios en España.", date: "2026-06-26", category: "GEO", tags: ["geo","chatgpt","posicionamiento-ia","perplexity","seo-local"], relatedSlugs: ["geo-posicionamiento-ia","ha-muerto-el-seo-con-la-ia"] },
  { slug: "cuanto-cuesta-agencia-marketing-digital-espana-2026", title: "Cuánto cuesta una agencia de marketing digital en España en 2026", excerpt: "Precios reales de agencias de marketing digital en España 2026: SEO, Google Ads y redes sociales. Lo que incluye cada rango y cómo no equivocarte al elegir.", date: "2026-06-26", category: "Estrategia Digital", tags: ["agencia-marketing-digital","precios","seo","google-ads","pymes"], relatedSlugs: ["seo-o-google-ads-que-conviene-mas","auditoria-seo-basica"] },
  { slug: "seo-para-clinicas-centros-salud-captar-pacientes-google", title: "SEO para clínicas y centros de salud: cómo captar pacientes en Google", excerpt: "El 74% de los pacientes busca en Google antes de llamar. SEO específico para clínicas dentales, fisioterapia y centros de salud en España. Capta más pacientes desde el primer mes.", date: "2026-06-26", category: "SEO", tags: ["seo-clinicas","seo-local","google-business-profile","salud","captacion-pacientes"], relatedSlugs: ["seo-local-empresas-servicios","google-my-business-empresas-guia"] },
  { slug: "woocommerce-vs-shopify-cual-elegir-tienda-online", title: "WooCommerce vs Shopify: cuál elegir para tu tienda online en España en 2026", excerpt: "WooCommerce es gratuito con control total. Shopify es más rápido de lanzar pero tiene comisiones. Comparativa honesta con recomendación por tipo de negocio y coste real a 3 años.", date: "2026-06-26", category: "Ecommerce", tags: ["woocommerce","shopify","tienda-online","ecommerce","plataformas"], relatedSlugs: ["seo-para-ecommerce-errores-que-frenan-ventas","google-merchant-center-ecommerce-guia"] },
  { slug: "seo-shopware-posicionar-tienda-google", title: "SEO para Shopware: cómo posicionar tu tienda en Google", excerpt: "Guía de SEO técnico para Shopware 6: URLs, navegación facetada, schema de producto, Core Web Vitals y fichas optimizadas para posicionar tu tienda en Google.", date: "2026-06-26", category: "Shopware", tags: ["shopware","seo-ecommerce","posicionamiento","tienda-online","schema"], relatedSlugs: ["woocommerce-vs-shopify-cual-elegir-tienda-online","seo-para-ecommerce-errores-que-frenan-ventas"] },
  { slug: "google-ads-shopware-campanas-que-venden", title: "Google Ads para Shopware: campañas que venden de verdad", excerpt: "Cómo montar Google Ads para tu tienda Shopware: tracking de conversiones, conexión con Merchant Center, Performance Max, Shopping y optimización por ROAS.", date: "2026-06-26", category: "Shopware", tags: ["shopware","google-ads","google-shopping","performance-max","merchant-center"], relatedSlugs: ["woocommerce-vs-shopify-cual-elegir-tienda-online","google-merchant-center-ecommerce-guia"] },
  { slug: "migrar-shopware-prestashop-woocommerce-seo", title: "Migrar a Shopware desde PrestaShop o WooCommerce sin perder SEO", excerpt: "Cómo migrar tu tienda a Shopware sin perder posicionamiento: auditoría de URLs, mapa de redirecciones 301, protocolo de lanzamiento y seguimiento post-migración.", date: "2026-06-26", category: "Shopware", tags: ["shopware","migracion","seo","prestashop","redirecciones-301"], relatedSlugs: ["woocommerce-vs-shopify-cual-elegir-tienda-online","seo-para-ecommerce-errores-que-frenan-ventas"] },
  { slug: "geo-shopware-agentic-commerce-chatgpt", title: "GEO para Shopware: vende desde ChatGPT con Agentic Commerce", excerpt: "Shopware 6.7.9 trae Agentic Commerce nativo. Prepara tu tienda con GEO para que ChatGPT y Perplexity recomienden y vendan tus productos directamente.", date: "2026-06-26", category: "Shopware", tags: ["shopware","geo","agentic-commerce","chatgpt","posicionamiento-ia"], relatedSlugs: ["geo-posicionamiento-ia-chatgpt-empresas-espana","woocommerce-vs-shopify-cual-elegir-tienda-online"] },
  { slug: "cro-shopware-optimizar-conversion-tienda", title: "CRO para Shopware: cómo optimizar la conversión de tu tienda", excerpt: "Sube la conversión de tu tienda Shopware: eventos GA4 clave, las 5 causas reales de abandono de carrito y optimización de fichas de producto y checkout.", date: "2026-06-26", category: "Shopware", tags: ["shopware","cro","conversion","tienda-online","abandono-carrito"], relatedSlugs: ["woocommerce-vs-shopify-cual-elegir-tienda-online","seo-para-ecommerce-errores-que-frenan-ventas"] },
  { slug: "por-que-aparecer-en-chatgpt-perplexity-gemini-importa-mas-que-el-seo-en-2026", title: "Por qué aparecer en ChatGPT y Gemini importa más que el SEO en 2026", excerpt: "Millones de personas ya no buscan en Google. Preguntan a ChatGPT, Perplexity o Gemini. Si tu negocio no aparece en sus respuestas, estás perdiendo clientes sin saberlo. Guía GEO 2026.", date: "2026-07-07", category: "GEO", tags: ["geo","chatgpt","perplexity","gemini","posicionamiento-ia"], relatedSlugs: ["geo-posicionamiento-ia","seo-posicionamiento-web-organico","geo-vs-seo-diferencias","ha-muerto-el-seo-con-la-ia"] },
  { slug: "como-optimizar-tu-contenido-para-que-la-ia-te-cite-guia-geo-2026", title: "Cómo optimizar tu contenido para que la IA te cite: guía GEO 2026", excerpt: "Guía técnica y práctica de GEO para pymes. Aprende a estructurar tu contenido, implementar schema markup avanzado, configurar llms.txt y construir autoridad semántica para aparecer en ChatGPT, Gemini y Perplexity.", date: "2026-07-07", category: "GEO", tags: ["geo","llms-txt","schema","contenido","posicionamiento-ia"], relatedSlugs: ["geo-posicionamiento-ia","seo-posicionamiento-web-organico","seo-local-empresas-servicios","por-que-aparecer-en-chatgpt-perplexity-gemini-importa-mas-que-el-seo-en-2026"] },
  { slug: "geo-para-pymes-como-aparecer-en-respuestas-ia-sin-ser-una-gran-marca", title: "GEO para pymes: cómo aparecer en ChatGPT sin ser una gran marca", excerpt: "Las pymes tienen una ventaja real en GEO: la especificidad de nicho. Guía práctica para que cualquier negocio pequeño aparezca en las respuestas de ChatGPT, Gemini y Perplexity.", date: "2026-07-07", category: "GEO", tags: ["geo","pymes","posicionamiento-ia","chatgpt"], relatedSlugs: ["geo-posicionamiento-ia","seo-local-empresas-servicios","seo-posicionamiento-web-organico","como-optimizar-tu-contenido-para-que-la-ia-te-cite-guia-geo-2026"] },
  { slug: "actualizaciones-algoritmo-google-2026-que-ha-cambiado-y-como-afecta-tu-web", title: "Actualizaciones del algoritmo de Google en 2026: qué ha cambiado y cómo afecta a tu web", excerpt: "Google ha lanzado varias actualizaciones de algoritmo en 2026 con foco en experiencia de usuario, contenido de IA y señales E-E-A-T. Analizamos qué ha cambiado y qué tienes que hacer.", date: "2026-07-07", category: "SEO", tags: ["seo","algoritmo-google","ai-overviews","e-e-a-t"], relatedSlugs: ["seo-posicionamiento-web-organico","auditoria-seo-basica","geo-posicionamiento-ia","ha-muerto-el-seo-con-la-ia"] },
  { slug: "seo-en-la-era-de-la-ia-como-posicionarse-cuando-google-usa-gemini", title: "SEO en la era de la IA: cómo posicionarse cuando Google usa Gemini para responder", excerpt: "Google ya no es solo un buscador. Es un motor de respuestas generativas con Gemini. Cómo adaptar tu estrategia SEO para que tu web siga captando tráfico cuando la IA responde antes que tú.", date: "2026-07-07", category: "SEO", tags: ["seo","gemini","ai-overviews","ia"], relatedSlugs: ["seo-posicionamiento-web-organico","geo-posicionamiento-ia","geo-vs-seo-diferencias","actualizaciones-algoritmo-google-2026-que-ha-cambiado-y-como-afecta-tu-web"] },
  { slug: "linkedin-para-pymes-espanolas-en-2026-guia-practica-para-generar-leads", title: "LinkedIn para pymes españolas en 2026: guía práctica para generar leads", excerpt: "LinkedIn ha cambiado más en 2026 que en los 5 años anteriores. Nuevo algoritmo, vídeo como formato dominante, Employee Generated Content y social selling. Cómo aprovecharlo si eres una pyme.", date: "2026-07-07", category: "Social Media", tags: ["linkedin","redes-sociales","b2b","leads","pymes"], relatedSlugs: ["smm-social-media-marketing","marketing-de-contenidos","como-generar-leads-calidad-pyme","redes-sociales-para-empresas-2026-que-funciona-de-verdad-segun-los-datos"] },
  { slug: "redes-sociales-para-empresas-2026-que-funciona-de-verdad-segun-los-datos", title: "Redes sociales para empresas en 2026: qué funciona de verdad según los datos", excerpt: "El estudio Social Media 2026 de Cyberclick y Metricool analiza millones de publicaciones. TikTok lidera en impresiones, Instagram en estabilidad, LinkedIn en B2B. Qué significa para tu estrategia.", date: "2026-07-07", category: "Social Media", tags: ["redes-sociales","estrategia","tiktok","instagram","datos"], relatedSlugs: ["smm-social-media-marketing","linkedin-para-pymes-espanolas-en-2026-guia-practica-para-generar-leads","marketing-de-contenidos","sem-publicidad-ppc"] },
  { slug: "cuota-autonomos-2026-todo-lo-que-tienes-que-saber", title: "Cuota de autónomos 2026: tabla de tramos, MEI y lo que ha cambiado", excerpt: "Las cuotas de autónomos 2026 se mantienen iguales a 2025 por prórroga del Gobierno, salvo el MEI que sube al 0,9%. Tabla completa de tramos, tarifa plana de 80€ y cómo cambiar tu base hasta 6 veces al año.", date: "2026-07-07", category: "Marketing Digital", tags: ["autonomos","cuota","mei","fiscal","seguridad-social"], relatedSlugs: ["como-darse-de-alta-autonomo","factura-electronica-obligatoria-autonomos-pymes","marketing-digital-para-autonomos-en-2026-como-conseguir-clientes-sin-agencia"] },
  { slug: "marketing-digital-para-autonomos-en-2026-como-conseguir-clientes-sin-agencia", title: "Marketing digital para autónomos en 2026: cómo conseguir clientes sin contratar una agencia", excerpt: "Los autónomos tienen más herramientas que nunca para conseguir clientes online por su cuenta. Guía práctica: SEO local, Google Business Profile, LinkedIn y contenido para autónomos en 2026.", date: "2026-07-07", category: "Marketing Digital", tags: ["autonomos","marketing-digital","seo-local","captacion"], relatedSlugs: ["seo-local-empresas-servicios","google-business-profile","diseno-de-paginas-web","sem-publicidad-ppc","cuota-autonomos-2026-todo-lo-que-tienes-que-saber"] },
  { slug: "agentes-ia-marketing-que-son-como-usarlos-en-tu-negocio", title: "Agentes de IA para marketing: qué son y cómo puede usarlos una pyme", excerpt: "Los agentes de IA ya no son ciencia ficción. En 2026, herramientas accesibles permiten que cualquier pyme automatice tareas de marketing con agentes que trabajan de forma autónoma. Guía práctica.", date: "2026-07-07", category: "IA", tags: ["ia","agentes-ia","automatizacion","marketing"], relatedSlugs: ["ia-aplicada-al-marketing","geo-posicionamiento-ia","chatgpt-para-marketing-digital","herramientas-ia-para-marketing-digital-2026-las-que-realmente-funcionan"] },
  { slug: "herramientas-ia-para-marketing-digital-2026-las-que-realmente-funcionan", title: "Herramientas de IA para marketing digital en 2026: las que realmente funcionan", excerpt: "No todas las herramientas de IA para marketing merecen el tiempo que cuesta aprenderlas. Análisis honesto de las que aportan valor real a pymes y agencias en 2026.", date: "2026-07-07", category: "IA", tags: ["ia","herramientas","chatgpt","automatizacion","marketing"], relatedSlugs: ["ia-aplicada-al-marketing","chatgpt-para-marketing-digital","agentes-ia-marketing-que-son-como-usarlos-en-tu-negocio","geo-posicionamiento-ia"] },
  { slug: "como-la-ia-esta-cambiando-el-marketing-digital-para-siempre", title: "Cómo la IA está cambiando el marketing digital para siempre (y qué significa para tu negocio)", excerpt: "La IA ya no es una tendencia en marketing: es la infraestructura. Más del 70% de las interacciones de marketing digital estarán influenciadas por IA en 2026. Qué cambia, qué no cambia y qué tienes que hacer.", date: "2026-07-07", category: "IA", tags: ["ia","marketing-digital","tendencias","estrategia"], relatedSlugs: ["ia-aplicada-al-marketing","chatgpt-para-marketing-digital","herramientas-ia-para-marketing-digital-2026-las-que-realmente-funcionan","geo-posicionamiento-ia","agentes-ia-marketing-que-son-como-usarlos-en-tu-negocio"] },
  { slug: "que-es-un-chatbot-para-empresas-y-por-que-lo-necesitas-en-2026", title: "Qué es un chatbot para empresas y por qué lo necesitas en 2026", excerpt: "Un chatbot para empresas ya no es tecnología de grandes corporaciones. En 2026, las pymes españolas que automatizan su atención al cliente con IA reducen costes, captan más leads y venden más.", date: "2026-07-07", category: "IA y Automatización", tags: ["chatbot","ia","automatización","pymes"], relatedSlugs: ["ia-aplicada-al-marketing","chatgpt-para-marketing-digital","agentes-ia-marketing-que-son-como-usarlos-en-tu-negocio"] },
  { slug: "chatbot-para-tienda-online-guia-completa-2026", title: "Chatbot para tienda online: guía completa para vender más y atender mejor en 2026", excerpt: "Un chatbot para tienda online puede atender consultas 24/7, recuperar carritos abandonados, responder preguntas de producto y gestionar el estado de pedidos.", date: "2026-07-07", category: "Ecommerce", tags: ["chatbot","tienda online","ecommerce","woocommerce"], relatedSlugs: ["diseno-de-paginas-web/diseno-tiendas-online","seo-para-ecommerce-errores-que-frenan-ventas","migrar-shopify-woocommerce"] },
  { slug: "chatbot-wordpress-como-instalarlo-que-evitar", title: "Chatbot para WordPress: cómo instalarlo, qué evitar y qué esperar", excerpt: "WordPress tiene decenas de plugins de chatbot. La mayoría no merece el tiempo que cuesta probarlos. Guía honesta sobre qué funciona de verdad en 2026.", date: "2026-07-07", category: "Diseño Web", tags: ["chatbot","wordpress","plugins","ia"], relatedSlugs: ["diseno-de-paginas-web","ia-aplicada-al-marketing","que-es-un-chatbot-para-empresas-y-por-que-lo-necesitas-en-2026"] },
  { slug: "chatbot-ia-rgpd-ai-act-cumplimiento-legal-espana", title: "Chatbot con IA y cumplimiento legal en España: RGPD, AI Act y lo que cambia en agosto de 2026", excerpt: "En agosto de 2026 entran en vigor las principales obligaciones del AI Act para chatbots. Qué tienes que hacer para cumplir en España y por qué el cumplimiento es una ventaja competitiva.", date: "2026-07-07", category: "IA y Automatización", tags: ["chatbot","rgpd","ai act","cumplimiento legal","ia"], relatedSlugs: ["ia-aplicada-al-marketing","geo-posicionamiento-ia","que-es-un-chatbot-para-empresas-y-por-que-lo-necesitas-en-2026"] },
  { slug: "atencion-cliente-24-7-pymes-sin-contratar-personal", title: "Atención al cliente 24/7 para pymes: cómo conseguirlo sin contratar más personal", excerpt: "Las grandes empresas llevan años ofreciendo atención al cliente 24/7. En 2026, las pymes españolas pueden conseguir lo mismo con chatbots de IA, sin contratar más personal.", date: "2026-07-07", category: "IA y Automatización", tags: ["chatbot","atención al cliente","24/7","automatización","pymes"], relatedSlugs: ["ia-aplicada-al-marketing","como-generar-leads-calidad-pyme","que-es-un-chatbot-para-empresas-y-por-que-lo-necesitas-en-2026"] },
  { slug: "chatbot-para-clinicas-centros-salud-automatizar-citas", title: "Chatbot para clínicas y centros de salud: citas, preguntas y cumplimiento sanitario", excerpt: "Las clínicas y centros de salud reciben cientos de consultas repetitivas cada día. Un chatbot puede automatizar la gestión de citas, responder preguntas y cualificar pacientes.", date: "2026-07-07", category: "Marketing Digital", tags: ["chatbot","clínicas","salud","automatizar citas","ia"], relatedSlugs: ["diseno-web-para-clinicas","diseno-web-para-dentistas","seo-local-empresas-servicios"] },
  { slug: "cuanto-cuesta-un-chatbot-para-empresas-espana-2026", title: "Cuánto cuesta un chatbot para empresas en España en 2026: guía de precios reales", excerpt: "Los precios de los chatbots para empresas varían desde 0€ hasta miles de euros al mes. Guía de precios reales: qué cobran los líderes del mercado y cuándo sale rentable.", date: "2026-07-07", category: "IA y Automatización", tags: ["chatbot","precios","coste","ia","pymes"], relatedSlugs: ["ia-aplicada-al-marketing","herramientas-ia-para-marketing-digital-2026-las-que-realmente-funcionan","que-es-un-chatbot-para-empresas-y-por-que-lo-necesitas-en-2026"] },
  { slug: "chatbot-captacion-cualificacion-leads-guia-practica", title: "Cómo usar un chatbot para captar y cualificar leads: guía práctica", excerpt: "Un chatbot bien configurado puede captar leads 24/7, cualificarlos con preguntas estratégicas y pasarlos al CRM con contexto completo.", date: "2026-07-07", category: "Marketing Digital", tags: ["chatbot","leads","captación","crm","ia"], relatedSlugs: ["como-generar-leads-calidad-pyme","como-crear-landing-page-que-convierte","sem-publicidad-ppc"] },
  { slug: "chatbot-vs-live-chat-diferencias-cual-elegir-empresa", title: "Chatbot vs live chat: diferencias reales y cuál elegir para tu empresa", excerpt: "¿Chatbot o live chat? No son opciones excluyentes. Guía de las diferencias reales, cuándo conviene cada uno, y por qué la combinación correcta es mejor que elegir solo uno.", date: "2026-07-07", category: "IA y Automatización", tags: ["chatbot","live chat","atención al cliente","ia"], relatedSlugs: ["ia-aplicada-al-marketing","atencion-cliente-24-7-pymes-sin-contratar-personal","que-es-un-chatbot-para-empresas-y-por-que-lo-necesitas-en-2026"] },
  { slug: "como-elegir-chatbot-para-empresa-checklist-2026", title: "Cómo elegir el chatbot correcto para tu empresa: checklist completa para 2026", excerpt: "Antes de elegir un chatbot para tu empresa, hay 10 preguntas que debes responder. Esta checklist te ayuda a evitar los errores más frecuentes.", date: "2026-07-07", category: "Marketing Digital", tags: ["chatbot","ia","guía","pymes","comparativa"], relatedSlugs: ["ia-aplicada-al-marketing","que-es-un-chatbot-para-empresas-y-por-que-lo-necesitas-en-2026","chatbot-ia-rgpd-ai-act-cumplimiento-legal-espana"] },
];

function interleaveByCategory(items: BlogPost[]): BlogPost[] {
  const groups = new Map<string, BlogPost[]>();
  for (const it of items) {
    if (!groups.has(it.category)) groups.set(it.category, []);
    groups.get(it.category)!.push(it);
  }
  const result: BlogPost[] = [];
  let prev: string | null = null;
  while (result.length < items.length) {
    let cands = [...groups.entries()].filter(([c, g]) => g.length > 0 && c !== prev);
    if (cands.length === 0) cands = [...groups.entries()].filter(([, g]) => g.length > 0);
    cands.sort((a, b) => b[1].length - a[1].length);
    const chosen = cands[0][0];
    result.push(groups.get(chosen)!.shift()!);
    prev = chosen;
  }
  return result;
}

export function getVisiblePosts(): BlogPost[] {
  const sorted = [...allPosts]
    .filter(p => p.category !== "Autónomos")
    .sort((a, b) => b.date.localeCompare(a.date));
  const head = interleaveByCategory(sorted.slice(0, 9));
  return [...head, ...sorted.slice(9)];
}

export function getLatestPosts(n: number): BlogPost[] {
  return getVisiblePosts().slice(0, n);
}

export function getRelatedPosts(currentSlug: string, n: number): BlogPost[] {
  const current = allPosts.find(p => p.slug === currentSlug);
  if (!current) return getLatestPosts(n);
  const byRelated = allPosts.filter(p => current.relatedSlugs.includes(p.slug));
  if (byRelated.length >= n) return byRelated.slice(0, n);
  const byTag = allPosts.filter(p => p.slug !== currentSlug && !current.relatedSlugs.includes(p.slug) && p.tags.some(t => current.tags.includes(t)));
  return [...byRelated, ...byTag].slice(0, n);
}

export function getPostsByCategory(category: string, n: number): BlogPost[] {
  return allPosts.filter(p => p.category.toLowerCase().includes(category.toLowerCase())).slice(0, n).concat(getLatestPosts(n)).filter((v,i,a)=>a.findIndex(p=>p.slug===v.slug)===i).slice(0,n);
}
